name: Flutter Android APK Build

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Create .env file
      run: |
        touch .env
        echo "${{secrets.BUILD}}" >> .env

    # Install Java 17
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    # Step 2: Set up Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: master # or: beta, master (or main)
    - run: flutter --version

    # Step 3: Cache Flutter dependencies
    - name: Cache Flutter Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.pub-cache
          .dart_tool
        key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pub-cache-

    # Step 4: Install dependencies
    - name: Install Dependencies
      run: flutter pub get

    # Step 5: Force-update Gradle and AGP version
    - name: Update Gradle & Android Gradle Plugin
      run: |
        # Update AGP version in build.gradle
        sed -i 's/com.android.tools.build:gradle:[^"]*/com.android.tools.build:gradle:8.6.0/' android/build.gradle

        # Update Gradle wrapper version in gradle-wrapper.properties
        sed -i 's|distributionUrl=.*|distributionUrl=https\://services.gradle.org/distributions/gradle-8.7-all.zip|' android/gradle/wrapper/gradle-wrapper.properties

    # Step 6: Run Flutter build
    - name: Build APK
      run: flutter build apk --release

    # Step 7: Upload the APK as an artifact
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk

    # Step 8: Create releases
    - name: Upload Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/app/outputs/flutter-apk/app-release.apk
        token: ${{secrets.ACTIONS}}
        release_name: Nihongo version ${{github.ref}}
        body: |
          Release APK for version ${{github.ref}}
        tag: ${{github.ref}}
        draft: false
        prerelease: false
