name: Flutter Android APK Build

on:
  push:
    branches:
      - pipelines
  pull_request:
    branches:
      - pipelines

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Create .env file
      run: |
        touch .env
        echo "${{secrets.BUILD}}" >> .env

    # Install Java 17
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    # Step 2: Set up Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: master # or: beta, master (or main)
    - run: flutter --version

    # Step 3: Cache Flutter dependencies
    - name: Cache Flutter Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.pub-cache
          .dart_tool
        key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pub-cache-

    # Step 4: Install dependencies
    - name: Install Dependencies
      run: flutter pub get

    # Step 5: Run Flutter build
    - name: Build APK
      run: flutter build apk --release

    # Step 6: Upload the APK as an artifact
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
